export const USER_AUTH_SUCCESS = 'USER_SAVE_SUCCESS';
export const USER_AUTH_FAIL = 'USER_SAVE_FAIL';
export const USER_AUTH = 'USER_AUTH';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_CHECK_TOKEN = 'USER_CHECK_TOKEN';
